-- ============================================================================
-- InnaIT WIAM 5.0 - INNAIT_AUDIT Schema
-- V001: Audit events, admin actions, security incidents
-- Note: Partitioning removed - Oracle 23c Free does not support interval partitioning
--       PKs use single-column keys to match JPA entity @Id mappings
--       RESOURCE_ID/TARGET_ID changed to RAW(16), SERVICE_NAME added to AUDIT_EVENTS
-- ============================================================================

--------------------------------------------------------
-- AUDIT_EVENTS
--------------------------------------------------------
CREATE TABLE AUDIT_EVENTS (
    AUDIT_EVENT_ID       RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    CORRELATION_ID       RAW(16),
    EVENT_TYPE           VARCHAR2(100)     NOT NULL,
    EVENT_CATEGORY       VARCHAR2(30)      NOT NULL,
    ACTOR_ID             RAW(16),
    ACTOR_TYPE           VARCHAR2(50),
    ACTOR_IP             VARCHAR2(45),
    SUBJECT_ID           RAW(16),
    SUBJECT_TYPE         VARCHAR2(50),
    RESOURCE_TYPE        VARCHAR2(50),
    RESOURCE_ID          RAW(16),
    ACTION               VARCHAR2(50)      NOT NULL,
    OUTCOME              VARCHAR2(20)      DEFAULT 'SUCCESS' NOT NULL,
    DETAIL               CLOB              DEFAULT '{}',
    SERVICE_NAME         VARCHAR2(100),
    EVENT_TIME           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AUDIT_EVENT PRIMARY KEY (AUDIT_EVENT_ID),
    CONSTRAINT CHK_AE_CATEGORY CHECK (EVENT_CATEGORY IN ('AUTHENTICATION','AUTHORIZATION','USER_MANAGEMENT','CREDENTIAL','SESSION','POLICY','CONFIG','DIRECTORY_SYNC','SECURITY','SYSTEM')),
    CONSTRAINT CHK_AE_OUTCOME CHECK (OUTCOME IN ('SUCCESS','FAILURE','ERROR','DENIED')),
    CONSTRAINT CHK_AE_DETAIL CHECK (DETAIL IS JSON)
);

CREATE INDEX IDX_AE_TENANT ON AUDIT_EVENTS (TENANT_ID);
CREATE INDEX IDX_AE_CORR ON AUDIT_EVENTS (CORRELATION_ID);
CREATE INDEX IDX_AE_TYPE ON AUDIT_EVENTS (EVENT_TYPE);
CREATE INDEX IDX_AE_CATEGORY ON AUDIT_EVENTS (TENANT_ID, EVENT_CATEGORY);
CREATE INDEX IDX_AE_ACTOR ON AUDIT_EVENTS (ACTOR_ID);
CREATE INDEX IDX_AE_SUBJECT ON AUDIT_EVENTS (SUBJECT_ID);
CREATE INDEX IDX_AE_TIME ON AUDIT_EVENTS (TENANT_ID, EVENT_TIME DESC);

--------------------------------------------------------
-- ADMIN_ACTIONS (range-partitioned by ACTION_TIME, monthly)
--------------------------------------------------------
CREATE TABLE ADMIN_ACTIONS (
    ADMIN_ACTION_ID      RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    ADMIN_ID             RAW(16)           NOT NULL,
    ACTION_TYPE          VARCHAR2(100)     NOT NULL,
    TARGET_TYPE          VARCHAR2(50)      NOT NULL,
    TARGET_ID            RAW(16),
    BEFORE_STATE         CLOB,
    AFTER_STATE          CLOB,
    JUSTIFICATION        VARCHAR2(1000),
    ACTION_TIME          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ADMIN_ACTION PRIMARY KEY (ADMIN_ACTION_ID),
    CONSTRAINT CHK_AA_BEFORE CHECK (BEFORE_STATE IS JSON OR BEFORE_STATE IS NULL),
    CONSTRAINT CHK_AA_AFTER CHECK (AFTER_STATE IS JSON OR AFTER_STATE IS NULL)
);

CREATE INDEX IDX_AA_TENANT ON ADMIN_ACTIONS (TENANT_ID);
CREATE INDEX IDX_AA_ADMIN ON ADMIN_ACTIONS (ADMIN_ID);
CREATE INDEX IDX_AA_TYPE ON ADMIN_ACTIONS (ACTION_TYPE);
CREATE INDEX IDX_AA_TARGET ON ADMIN_ACTIONS (TARGET_TYPE, TARGET_ID);

--------------------------------------------------------
-- SECURITY_INCIDENTS (range-partitioned by DETECTED_AT, monthly)
--------------------------------------------------------
CREATE TABLE SECURITY_INCIDENTS (
    INCIDENT_ID          RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    INCIDENT_TYPE        VARCHAR2(50)      NOT NULL,
    SEVERITY             VARCHAR2(20)      NOT NULL,
    SOURCE_IP            VARCHAR2(45),
    ACCOUNT_ID           RAW(16),
    DESCRIPTION          VARCHAR2(4000)    NOT NULL,
    DETAIL               CLOB              DEFAULT '{}',
    STATUS               VARCHAR2(20)      DEFAULT 'OPEN' NOT NULL,
    RESOLVED_AT          TIMESTAMP WITH TIME ZONE,
    RESOLVED_BY          RAW(16),
    DETECTED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SEC_INCIDENT PRIMARY KEY (INCIDENT_ID),
    CONSTRAINT CHK_SI_SEVERITY CHECK (SEVERITY IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    CONSTRAINT CHK_SI_STATUS CHECK (STATUS IN ('OPEN','INVESTIGATING','RESOLVED','FALSE_POSITIVE')),
    CONSTRAINT CHK_SI_DETAIL CHECK (DETAIL IS JSON)
);

CREATE INDEX IDX_SI_TENANT ON SECURITY_INCIDENTS (TENANT_ID);
CREATE INDEX IDX_SI_TYPE ON SECURITY_INCIDENTS (INCIDENT_TYPE);
CREATE INDEX IDX_SI_SEVERITY ON SECURITY_INCIDENTS (TENANT_ID, SEVERITY);
CREATE INDEX IDX_SI_STATUS ON SECURITY_INCIDENTS (STATUS);
CREATE INDEX IDX_SI_ACCOUNT ON SECURITY_INCIDENTS (ACCOUNT_ID);
