-- ============================================================================
-- InnaIT WIAM 5.0 - INNAIT_CREDENTIAL Schema
-- V001: Password, FIDO, TOTP, soft-token, and backup-code credentials
-- ============================================================================

--------------------------------------------------------
-- PASSWORD_CREDENTIALS
--------------------------------------------------------
CREATE TABLE PASSWORD_CREDENTIALS (
    PASSWORD_CRED_ID     RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    ACCOUNT_ID           RAW(16)           NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    PASSWORD_HASH        VARCHAR2(512)     NOT NULL,
    HASH_ALGORITHM       VARCHAR2(30)      DEFAULT 'ARGON2ID' NOT NULL,
    SALT                 VARCHAR2(128),
    IS_ACTIVE            NUMBER(1)         DEFAULT 1 NOT NULL,
    MUST_CHANGE          NUMBER(1)         DEFAULT 0 NOT NULL,
    CREDENTIAL_STATUS    VARCHAR2(20)      DEFAULT 'ACTIVE' NOT NULL,
    EXPIRES_AT           TIMESTAMP WITH TIME ZONE,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PWD_CRED PRIMARY KEY (PASSWORD_CRED_ID),
    CONSTRAINT UQ_PWD_ACCT_ACTIVE UNIQUE (ACCOUNT_ID, IS_ACTIVE),
    CONSTRAINT CHK_PWD_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
    CONSTRAINT CHK_PWD_MUST CHECK (MUST_CHANGE IN (0, 1)),
    CONSTRAINT CHK_PWD_STATUS CHECK (CREDENTIAL_STATUS IN ('ACTIVE','EXPIRED','REVOKED','PENDING_RESET','COMPROMISED')),
    CONSTRAINT CHK_PWD_ALGO CHECK (HASH_ALGORITHM IN ('ARGON2ID','BCRYPT','SCRYPT','PBKDF2'))
);

CREATE INDEX IDX_PWDC_ACCOUNT ON PASSWORD_CREDENTIALS (ACCOUNT_ID);
CREATE INDEX IDX_PWDC_TENANT ON PASSWORD_CREDENTIALS (TENANT_ID);
CREATE INDEX IDX_PWDC_STATUS ON PASSWORD_CREDENTIALS (TENANT_ID, CREDENTIAL_STATUS);

--------------------------------------------------------
-- FIDO_CREDENTIALS
--------------------------------------------------------
CREATE TABLE FIDO_CREDENTIALS (
    FIDO_CRED_ID         RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    ACCOUNT_ID           RAW(16)           NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    CREDENTIAL_ID        VARCHAR2(1024)    NOT NULL,
    PUBLIC_KEY_COSE      BLOB              NOT NULL,
    AAGUID               RAW(16),
    SIGN_COUNT           NUMBER(19)        DEFAULT 0 NOT NULL,
    BACKUP_ELIGIBLE      NUMBER(1)         DEFAULT 0 NOT NULL,
    BACKUP_STATE         NUMBER(1)         DEFAULT 0 NOT NULL,
    DISPLAY_NAME         VARCHAR2(255),
    CREDENTIAL_STATUS    VARCHAR2(20)      DEFAULT 'ACTIVE' NOT NULL,
    LAST_USED_AT         TIMESTAMP WITH TIME ZONE,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_FIDO_CRED PRIMARY KEY (FIDO_CRED_ID),
    CONSTRAINT UQ_FIDO_CREDID UNIQUE (CREDENTIAL_ID),
    CONSTRAINT CHK_FIDO_BACKUP CHECK (BACKUP_ELIGIBLE IN (0, 1)),
    CONSTRAINT CHK_FIDO_BSTATE CHECK (BACKUP_STATE IN (0, 1)),
    CONSTRAINT CHK_FIDO_STATUS CHECK (CREDENTIAL_STATUS IN ('ACTIVE','EXPIRED','REVOKED','PENDING_RESET','COMPROMISED'))
);

CREATE INDEX IDX_FIDO_ACCOUNT ON FIDO_CREDENTIALS (ACCOUNT_ID);
CREATE INDEX IDX_FIDO_TENANT ON FIDO_CREDENTIALS (TENANT_ID);
CREATE INDEX IDX_FIDO_CREDID ON FIDO_CREDENTIALS (CREDENTIAL_ID);

--------------------------------------------------------
-- TOTP_CREDENTIALS
--------------------------------------------------------
CREATE TABLE TOTP_CREDENTIALS (
    TOTP_CRED_ID         RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    ACCOUNT_ID           RAW(16)           NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    ENCRYPTED_SECRET     RAW(256)          NOT NULL,
    SECRET_IV            RAW(16)           NOT NULL,
    SECRET_KEK_VERSION   NUMBER(5)         DEFAULT 1 NOT NULL,
    ALGORITHM            VARCHAR2(10)      DEFAULT 'SHA1' NOT NULL,
    DIGITS               NUMBER(1)         DEFAULT 6 NOT NULL,
    PERIOD_SECONDS       NUMBER(5)         DEFAULT 30 NOT NULL,
    CREDENTIAL_STATUS    VARCHAR2(20)      DEFAULT 'ACTIVE' NOT NULL,
    VERIFIED             NUMBER(1)         DEFAULT 0 NOT NULL,
    LAST_USED_AT         TIMESTAMP WITH TIME ZONE,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TOTP_CRED PRIMARY KEY (TOTP_CRED_ID),
    CONSTRAINT CHK_TOTP_ALGO CHECK (ALGORITHM IN ('SHA1','SHA256','SHA512')),
    CONSTRAINT CHK_TOTP_VERIFIED CHECK (VERIFIED IN (0, 1)),
    CONSTRAINT CHK_TOTP_STATUS CHECK (CREDENTIAL_STATUS IN ('ACTIVE','EXPIRED','REVOKED','PENDING_RESET','COMPROMISED'))
);

CREATE INDEX IDX_TOTP_ACCOUNT ON TOTP_CREDENTIALS (ACCOUNT_ID);
CREATE INDEX IDX_TOTP_TENANT ON TOTP_CREDENTIALS (TENANT_ID);

--------------------------------------------------------
-- SOFTTOKEN_CREDENTIALS
--------------------------------------------------------
CREATE TABLE SOFTTOKEN_CREDENTIALS (
    SOFTTOKEN_CRED_ID    RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    ACCOUNT_ID           RAW(16)           NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    DEVICE_ID            VARCHAR2(255)     NOT NULL,
    DEVICE_NAME          VARCHAR2(255),
    DEVICE_PLATFORM      VARCHAR2(20)      NOT NULL,
    PUBLIC_KEY           BLOB              NOT NULL,
    PUSH_TOKEN           VARCHAR2(512),
    ACTIVATION_STATUS    VARCHAR2(20)      DEFAULT 'PENDING' NOT NULL,
    LAST_USED_AT         TIMESTAMP WITH TIME ZONE,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SOFT_CRED PRIMARY KEY (SOFTTOKEN_CRED_ID),
    CONSTRAINT UQ_SOFT_DEVICE UNIQUE (DEVICE_ID),
    CONSTRAINT CHK_SOFT_PLATFORM CHECK (DEVICE_PLATFORM IN ('IOS','ANDROID','WINDOWS','MACOS','LINUX')),
    CONSTRAINT CHK_SOFT_STATUS CHECK (ACTIVATION_STATUS IN ('PENDING','ACTIVE','SUSPENDED','REVOKED'))
);

CREATE INDEX IDX_SOFT_ACCOUNT ON SOFTTOKEN_CREDENTIALS (ACCOUNT_ID);
CREATE INDEX IDX_SOFT_TENANT ON SOFTTOKEN_CREDENTIALS (TENANT_ID);
CREATE INDEX IDX_SOFT_DEVICE ON SOFTTOKEN_CREDENTIALS (DEVICE_ID);

--------------------------------------------------------
-- BACKUP_CODES
--------------------------------------------------------
CREATE TABLE BACKUP_CODES (
    BACKUP_CODE_ID       RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    ACCOUNT_ID           RAW(16)           NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    CODE_HASH            VARCHAR2(512)     NOT NULL,
    CODE_INDEX           NUMBER(3)         NOT NULL,
    STATUS               VARCHAR2(20)      DEFAULT 'UNUSED' NOT NULL,
    USED_AT              TIMESTAMP WITH TIME ZONE,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_BACKUP_CODE PRIMARY KEY (BACKUP_CODE_ID),
    CONSTRAINT UQ_BC_ACCT_IDX UNIQUE (ACCOUNT_ID, CODE_INDEX),
    CONSTRAINT CHK_BC_STATUS CHECK (STATUS IN ('UNUSED','USED','INVALIDATED'))
);

CREATE INDEX IDX_BC_ACCOUNT ON BACKUP_CODES (ACCOUNT_ID);
CREATE INDEX IDX_BC_TENANT ON BACKUP_CODES (TENANT_ID);
