-- ============================================================================
-- InnaIT WIAM 5.0 - INNAIT_CREDENTIAL Schema
-- V002: Password history, password policies, and backup code schema alignment
-- ============================================================================

--------------------------------------------------------
-- PASSWORD_HISTORY
--------------------------------------------------------
CREATE TABLE PASSWORD_HISTORY (
    PASSWORD_HISTORY_ID  RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    ACCOUNT_ID           RAW(16)           NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    PASSWORD_HASH        VARCHAR2(512)     NOT NULL,
    HASH_ALGORITHM       VARCHAR2(30)      DEFAULT 'ARGON2ID' NOT NULL,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PWD_HISTORY PRIMARY KEY (PASSWORD_HISTORY_ID),
    CONSTRAINT CHK_PWDH_ALGO CHECK (HASH_ALGORITHM IN ('ARGON2ID','BCRYPT','SCRYPT','PBKDF2'))
);

CREATE INDEX IDX_PWDH_ACCOUNT ON PASSWORD_HISTORY (ACCOUNT_ID);
CREATE INDEX IDX_PWDH_TENANT ON PASSWORD_HISTORY (TENANT_ID);
CREATE INDEX IDX_PWDH_CREATED ON PASSWORD_HISTORY (ACCOUNT_ID, CREATED_AT DESC);

--------------------------------------------------------
-- PASSWORD_POLICIES
--------------------------------------------------------
CREATE TABLE PASSWORD_POLICIES (
    PASSWORD_POLICY_ID   RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    POLICY_NAME          VARCHAR2(100)     NOT NULL,
    MIN_LENGTH           NUMBER(3)         DEFAULT 8 NOT NULL,
    MAX_LENGTH           NUMBER(3)         DEFAULT 128 NOT NULL,
    REQUIRE_UPPERCASE    NUMBER(1)         DEFAULT 1 NOT NULL,
    REQUIRE_LOWERCASE    NUMBER(1)         DEFAULT 1 NOT NULL,
    REQUIRE_DIGIT        NUMBER(1)         DEFAULT 1 NOT NULL,
    REQUIRE_SPECIAL      NUMBER(1)         DEFAULT 1 NOT NULL,
    HISTORY_COUNT        NUMBER(3)         DEFAULT 5 NOT NULL,
    MAX_AGE_DAYS         NUMBER(5)         DEFAULT 90 NOT NULL,
    LOCKOUT_THRESHOLD    NUMBER(3)         DEFAULT 5 NOT NULL,
    LOCKOUT_DURATION_MIN NUMBER(5)         DEFAULT 30 NOT NULL,
    IS_DEFAULT           NUMBER(1)         DEFAULT 0 NOT NULL,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PWD_POLICY PRIMARY KEY (PASSWORD_POLICY_ID),
    CONSTRAINT CHK_PP_UPPER CHECK (REQUIRE_UPPERCASE IN (0, 1)),
    CONSTRAINT CHK_PP_LOWER CHECK (REQUIRE_LOWERCASE IN (0, 1)),
    CONSTRAINT CHK_PP_DIGIT CHECK (REQUIRE_DIGIT IN (0, 1)),
    CONSTRAINT CHK_PP_SPECIAL CHECK (REQUIRE_SPECIAL IN (0, 1)),
    CONSTRAINT CHK_PP_DEFAULT CHECK (IS_DEFAULT IN (0, 1))
);

CREATE INDEX IDX_PP_TENANT ON PASSWORD_POLICIES (TENANT_ID);
-- Function-based unique index: only one default policy per tenant (Oracle doesn't support partial indexes)
CREATE UNIQUE INDEX IDX_PP_DEFAULT ON PASSWORD_POLICIES (
    CASE WHEN IS_DEFAULT = 1 THEN TENANT_ID ELSE NULL END
);

--------------------------------------------------------
-- BACKUP_CODES: add missing columns for BaseEntity alignment
--------------------------------------------------------
ALTER TABLE BACKUP_CODES ADD UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL;
ALTER TABLE BACKUP_CODES ADD VERSION NUMBER(19) DEFAULT 0 NOT NULL;
