-- ============================================================================
-- InnaIT WIAM 5.0 - INNAIT_CREDENTIAL Schema
-- V003: Device Registry, Assignments, Delivery Log, Lifecycle Events
-- ============================================================================

--------------------------------------------------------
-- DEVICE_REGISTRY
--------------------------------------------------------
CREATE TABLE DEVICE_REGISTRY (
    DEVICE_ID            RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    DEVICE_TYPE          VARCHAR2(30)      NOT NULL,
    DEVICE_CATEGORY      VARCHAR2(30),
    DEVICE_MODEL         VARCHAR2(100),
    DEVICE_VENDOR        VARCHAR2(100),
    DEVICE_SERIAL_NO     VARCHAR2(150),
    DEVICE_UNIQUE_REF    VARCHAR2(255)     NOT NULL,
    DEVICE_STATUS        VARCHAR2(30)      DEFAULT 'IN_STOCK' NOT NULL,
    OWNERSHIP_MODE       VARCHAR2(20)      DEFAULT 'DEDICATED' NOT NULL,
    PROCUREMENT_BATCH_ID RAW(16),
    PURCHASE_DATE        TIMESTAMP WITH TIME ZONE,
    WARRANTY_EXPIRY      TIMESTAMP WITH TIME ZONE,
    IS_ACTIVE            NUMBER(1)         DEFAULT 1 NOT NULL,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY           RAW(16),
    UPDATED_BY           RAW(16),
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_DEVICE_REG PRIMARY KEY (DEVICE_ID),
    CONSTRAINT CHK_DEV_TYPE CHECK (DEVICE_TYPE IN ('FIDO_KEY')),
    CONSTRAINT CHK_DEV_STATUS CHECK (DEVICE_STATUS IN ('IN_STOCK','ASSIGNED','ALLOCATED','PENDING_ACTIVATION','ACTIVE','SUSPENDED','REVOKED','RETURNED','RETIRED','LOST','DAMAGED','DECOMMISSIONED')),
    CONSTRAINT CHK_DEV_OWNER CHECK (OWNERSHIP_MODE IN ('DEDICATED')),
    CONSTRAINT CHK_DEV_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

-- Unique: DEVICE_SERIAL_NO per tenant (partial — only when NOT NULL)
CREATE UNIQUE INDEX UQ_DEV_SERIAL_TENANT ON DEVICE_REGISTRY (TENANT_ID, DEVICE_SERIAL_NO);

-- Unique: DEVICE_UNIQUE_REF per tenant
CREATE UNIQUE INDEX UQ_DEV_REF_TENANT ON DEVICE_REGISTRY (TENANT_ID, DEVICE_UNIQUE_REF);

CREATE INDEX IDX_DEVREG_TENANT ON DEVICE_REGISTRY (TENANT_ID);
CREATE INDEX IDX_DEVREG_STATUS ON DEVICE_REGISTRY (DEVICE_STATUS);
CREATE INDEX IDX_DEVREG_TYPE ON DEVICE_REGISTRY (DEVICE_TYPE);
CREATE INDEX IDX_DEVREG_BATCH ON DEVICE_REGISTRY (PROCUREMENT_BATCH_ID);

--------------------------------------------------------
-- DEVICE_ASSIGNMENTS
--------------------------------------------------------
CREATE TABLE DEVICE_ASSIGNMENTS (
    DEVICE_ASSIGNMENT_ID RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    DEVICE_ID            RAW(16)           NOT NULL,
    USER_ID              RAW(16),
    ACCOUNT_ID           RAW(16)           NOT NULL,
    ASSIGNMENT_TYPE      VARCHAR2(20)      DEFAULT 'PRIMARY' NOT NULL,
    ASSIGNMENT_STATUS    VARCHAR2(20)      DEFAULT 'PENDING' NOT NULL,
    ASSIGNED_AT          TIMESTAMP WITH TIME ZONE,
    EFFECTIVE_FROM       TIMESTAMP WITH TIME ZONE,
    EFFECTIVE_TO         TIMESTAMP WITH TIME ZONE,
    DELIVERY_STATUS      VARCHAR2(20),
    ASSIGNED_BY          RAW(16),
    APPROVED_BY          RAW(16),
    REVOKED_BY           RAW(16),
    REVOKED_AT           TIMESTAMP WITH TIME ZONE,
    REVOCATION_REASON    VARCHAR2(255),
    IS_ACTIVE            NUMBER(1)         DEFAULT 1 NOT NULL,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_DEV_ASSIGN PRIMARY KEY (DEVICE_ASSIGNMENT_ID),
    CONSTRAINT FK_DEVASSIGN_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE_REGISTRY (DEVICE_ID),
    CONSTRAINT CHK_ASSIGN_TYPE CHECK (ASSIGNMENT_TYPE IN ('PRIMARY')),
    CONSTRAINT CHK_ASSIGN_STATUS CHECK (ASSIGNMENT_STATUS IN ('PENDING','ALLOCATED','ACTIVE','SUSPENDED','REVOKED','EXPIRED','RETURNED')),
    CONSTRAINT CHK_ASSIGN_DELIV CHECK (DELIVERY_STATUS IS NULL OR DELIVERY_STATUS IN ('PENDING_DISPATCH','DISPATCHED','DELIVERED','ACKNOWLEDGED')),
    CONSTRAINT CHK_ASSIGN_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

-- Only one active assignment per device (function-based index — Oracle ignores NULLs)
CREATE UNIQUE INDEX UQ_DEVASSIGN_ACTIVE ON DEVICE_ASSIGNMENTS (
    CASE WHEN IS_ACTIVE = 1 THEN DEVICE_ID ELSE NULL END
);

CREATE INDEX IDX_DEVASSIGN_TENANT ON DEVICE_ASSIGNMENTS (TENANT_ID);
CREATE INDEX IDX_DEVASSIGN_DEVICE ON DEVICE_ASSIGNMENTS (DEVICE_ID);
CREATE INDEX IDX_DEVASSIGN_ACCOUNT ON DEVICE_ASSIGNMENTS (ACCOUNT_ID);
CREATE INDEX IDX_DEVASSIGN_USER ON DEVICE_ASSIGNMENTS (USER_ID);
CREATE INDEX IDX_DEVASSIGN_STATUS ON DEVICE_ASSIGNMENTS (ASSIGNMENT_STATUS);

--------------------------------------------------------
-- DEVICE_DELIVERY_LOG
--------------------------------------------------------
CREATE TABLE DEVICE_DELIVERY_LOG (
    DELIVERY_LOG_ID      RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    DEVICE_ID            RAW(16)           NOT NULL,
    DEVICE_ASSIGNMENT_ID RAW(16)           NOT NULL,
    EVENT_TYPE           VARCHAR2(30)      NOT NULL,
    EVENT_TIME           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    HANDLED_BY           RAW(16),
    COMMENTS             VARCHAR2(1000),
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_DEL_LOG PRIMARY KEY (DELIVERY_LOG_ID),
    CONSTRAINT FK_DELLOG_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE_REGISTRY (DEVICE_ID),
    CONSTRAINT FK_DELLOG_ASSIGN FOREIGN KEY (DEVICE_ASSIGNMENT_ID) REFERENCES DEVICE_ASSIGNMENTS (DEVICE_ASSIGNMENT_ID),
    CONSTRAINT CHK_DELLOG_TYPE CHECK (EVENT_TYPE IN ('PACKED','DISPATCHED','DELIVERED','ACKNOWLEDGED','RETURN_INITIATED','RETURNED'))
);

CREATE INDEX IDX_DELLOG_TENANT ON DEVICE_DELIVERY_LOG (TENANT_ID);
CREATE INDEX IDX_DELLOG_DEVICE ON DEVICE_DELIVERY_LOG (DEVICE_ID);
CREATE INDEX IDX_DELLOG_ASSIGN ON DEVICE_DELIVERY_LOG (DEVICE_ASSIGNMENT_ID);

--------------------------------------------------------
-- DEVICE_LIFECYCLE_EVENTS
--------------------------------------------------------
CREATE TABLE DEVICE_LIFECYCLE_EVENTS (
    DEVICE_EVENT_ID      RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    DEVICE_ID            RAW(16)           NOT NULL,
    EVENT_TYPE           VARCHAR2(50)      NOT NULL,
    OLD_STATUS           VARCHAR2(30),
    NEW_STATUS           VARCHAR2(30),
    EVENT_TIME           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    ACTOR_ID             RAW(16),
    DETAIL               CLOB,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_DEV_EVENT PRIMARY KEY (DEVICE_EVENT_ID),
    CONSTRAINT FK_DEVEV_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE_REGISTRY (DEVICE_ID),
    CONSTRAINT CHK_DEVEV_DETAIL CHECK (DETAIL IS JSON OR DETAIL IS NULL)
);

CREATE INDEX IDX_DEVEV_TENANT ON DEVICE_LIFECYCLE_EVENTS (TENANT_ID);
CREATE INDEX IDX_DEVEV_DEVICE ON DEVICE_LIFECYCLE_EVENTS (DEVICE_ID);
CREATE INDEX IDX_DEVEV_TYPE ON DEVICE_LIFECYCLE_EVENTS (EVENT_TYPE);
CREATE INDEX IDX_DEVEV_TIME ON DEVICE_LIFECYCLE_EVENTS (EVENT_TIME);
