-- ============================================================================
-- InnaIT WIAM 5.0 - INNAIT_CREDENTIAL Schema
-- V004: Account Bootstrap State and Magic Link Events
-- ============================================================================

--------------------------------------------------------
-- ACCOUNT_BOOTSTRAP_STATE
--------------------------------------------------------
CREATE TABLE ACCOUNT_BOOTSTRAP_STATE (
    BOOTSTRAP_STATE_ID       RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID                RAW(16)           NOT NULL,
    ACCOUNT_ID               RAW(16)           NOT NULL,
    USER_ID                  RAW(16)           NOT NULL,
    BOOTSTRAP_METHOD         VARCHAR2(30)      DEFAULT 'MAGIC_LINK' NOT NULL,
    BOOTSTRAP_ENABLED        NUMBER(1)         DEFAULT 1 NOT NULL,
    FIRST_LOGIN_PENDING      NUMBER(1)         DEFAULT 1 NOT NULL,
    FIDO_ENROLLED            NUMBER(1)         DEFAULT 0 NOT NULL,
    MAGIC_LINK_LAST_SENT_AT  TIMESTAMP WITH TIME ZONE,
    MAGIC_LINK_LAST_VERIFIED_AT TIMESTAMP WITH TIME ZONE,
    MAGIC_LINK_EXPIRES_AT    TIMESTAMP WITH TIME ZONE,
    MAGIC_LINK_USED_AT       TIMESTAMP WITH TIME ZONE,
    LAST_MAGIC_LINK_TXN_ID  RAW(16),
    CREATED_AT               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION                  NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_BOOTSTRAP_STATE PRIMARY KEY (BOOTSTRAP_STATE_ID),
    CONSTRAINT CHK_BS_METHOD CHECK (BOOTSTRAP_METHOD IN ('MAGIC_LINK')),
    CONSTRAINT CHK_BS_ENABLED CHECK (BOOTSTRAP_ENABLED IN (0, 1)),
    CONSTRAINT CHK_BS_FIRSTLOGIN CHECK (FIRST_LOGIN_PENDING IN (0, 1)),
    CONSTRAINT CHK_BS_FIDO CHECK (FIDO_ENROLLED IN (0, 1))
);

-- One bootstrap state per account per tenant
CREATE UNIQUE INDEX UQ_BOOTSTRAP_ACCT ON ACCOUNT_BOOTSTRAP_STATE (TENANT_ID, ACCOUNT_ID);

CREATE INDEX IDX_BS_TENANT ON ACCOUNT_BOOTSTRAP_STATE (TENANT_ID);
CREATE INDEX IDX_BS_ACCOUNT ON ACCOUNT_BOOTSTRAP_STATE (ACCOUNT_ID);
CREATE INDEX IDX_BS_USER ON ACCOUNT_BOOTSTRAP_STATE (USER_ID);
CREATE INDEX IDX_BS_PENDING ON ACCOUNT_BOOTSTRAP_STATE (FIRST_LOGIN_PENDING, BOOTSTRAP_ENABLED);

--------------------------------------------------------
-- AUTH_MAGIC_LINK_EVENTS
--------------------------------------------------------
CREATE TABLE AUTH_MAGIC_LINK_EVENTS (
    MAGIC_LINK_EVENT_ID  RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    ACCOUNT_ID           RAW(16)           NOT NULL,
    USER_ID              RAW(16)           NOT NULL,
    AUTH_TXN_ID          RAW(16),
    EVENT_STATUS         VARCHAR2(20)      NOT NULL,
    IP_ADDRESS           VARCHAR2(100),
    USER_AGENT           VARCHAR2(1000),
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DETAIL               CLOB,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ML_EVENT PRIMARY KEY (MAGIC_LINK_EVENT_ID),
    CONSTRAINT CHK_MLE_STATUS CHECK (EVENT_STATUS IN ('SENT','VERIFIED','FAILED','EXPIRED','REUSED','BLOCKED')),
    CONSTRAINT CHK_MLE_DETAIL CHECK (DETAIL IS JSON OR DETAIL IS NULL)
);

CREATE INDEX IDX_MLE_TENANT ON AUTH_MAGIC_LINK_EVENTS (TENANT_ID);
CREATE INDEX IDX_MLE_ACCOUNT ON AUTH_MAGIC_LINK_EVENTS (ACCOUNT_ID);
CREATE INDEX IDX_MLE_USER ON AUTH_MAGIC_LINK_EVENTS (USER_ID);
CREATE INDEX IDX_MLE_TXN ON AUTH_MAGIC_LINK_EVENTS (AUTH_TXN_ID);
CREATE INDEX IDX_MLE_STATUS ON AUTH_MAGIC_LINK_EVENTS (EVENT_STATUS);
