-- ============================================================================
-- InnaIT WIAM 5.0 - INNAIT_AUTHN Schema
-- V003: Add bootstrap/magic-link auth states and MAGIC_LINK factor type
-- ============================================================================

ALTER TABLE AUTH_TRANSACTIONS DROP CONSTRAINT CHK_ATXN_STATE;

ALTER TABLE AUTH_TRANSACTIONS ADD CONSTRAINT CHK_ATXN_STATE
    CHECK (CURRENT_STATE IN (
        'INITIATED','IDENTIFIER_COLLECTED','PRIMARY_CHALLENGE','PRIMARY_VERIFIED',
        'MFA_REQUIRED','MFA_CHALLENGE','MFA_VERIFIED',
        'MAGIC_LINK_SENT','ONBOARDING_REQUIRED','FIDO_ENROLLMENT_IN_PROGRESS',
        'COMPLETED','FAILED','ABORTED'
    ));

-- Add MAGIC_LINK to challenge type constraint
ALTER TABLE AUTH_CHALLENGES DROP CONSTRAINT CHK_ACHL_TYPE;

ALTER TABLE AUTH_CHALLENGES ADD CONSTRAINT CHK_ACHL_TYPE
    CHECK (CHALLENGE_TYPE IN ('PASSWORD','FIDO','TOTP','OTP_EMAIL','OTP_SMS','PUSH','MAGIC_LINK'));
