-- ============================================================================
-- InnaIT WIAM 5.0 - INNAIT_CONFIG Schema
-- V001: Feature flags, connectors, system settings
-- ============================================================================

--------------------------------------------------------
-- FEATURE_FLAGS
--------------------------------------------------------
CREATE TABLE FEATURE_FLAGS (
    FEATURE_FLAG_ID      RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    FLAG_KEY             VARCHAR2(100)     NOT NULL,
    FLAG_VALUE           NUMBER(1)         DEFAULT 0 NOT NULL,
    DESCRIPTION          VARCHAR2(500),
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_FEATURE_FLAG PRIMARY KEY (FEATURE_FLAG_ID),
    CONSTRAINT UQ_FF_TENANT_KEY UNIQUE (TENANT_ID, FLAG_KEY),
    CONSTRAINT CHK_FF_VALUE CHECK (FLAG_VALUE IN (0, 1))
);

CREATE INDEX IDX_FF_TENANT ON FEATURE_FLAGS (TENANT_ID);

--------------------------------------------------------
-- CONNECTORS
--------------------------------------------------------
CREATE TABLE CONNECTORS (
    CONNECTOR_ID         RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    CONNECTOR_NAME       VARCHAR2(255)     NOT NULL,
    CONNECTOR_TYPE       VARCHAR2(30)      NOT NULL,
    ENCRYPTED_CONFIG     CLOB              NOT NULL,
    STATUS               VARCHAR2(20)      DEFAULT 'ACTIVE' NOT NULL,
    LAST_SYNC_AT         TIMESTAMP WITH TIME ZONE,
    LAST_SYNC_STATUS     VARCHAR2(20),
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CONNECTOR PRIMARY KEY (CONNECTOR_ID),
    CONSTRAINT CHK_CONN_TYPE CHECK (CONNECTOR_TYPE IN ('LDAP','ACTIVE_DIRECTORY','AZURE_AD','GOOGLE_WORKSPACE','OKTA','SCIM','HR_FEED','SAML_IDP','OIDC_OP')),
    CONSTRAINT CHK_CONN_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE','ERROR','CONFIGURING')),
    CONSTRAINT CHK_CONN_CONFIG CHECK (ENCRYPTED_CONFIG IS JSON)
);

CREATE INDEX IDX_CONN_TENANT ON CONNECTORS (TENANT_ID);
CREATE INDEX IDX_CONN_TYPE ON CONNECTORS (TENANT_ID, CONNECTOR_TYPE);

--------------------------------------------------------
-- SYSTEM_SETTINGS
--------------------------------------------------------
CREATE TABLE SYSTEM_SETTINGS (
    SETTING_ID           RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16),
    SETTING_KEY          VARCHAR2(200)     NOT NULL,
    SETTING_VALUE        VARCHAR2(4000)    NOT NULL,
    VALUE_TYPE           VARCHAR2(20)      DEFAULT 'STRING' NOT NULL,
    DESCRIPTION          VARCHAR2(500),
    IS_SENSITIVE         NUMBER(1)         DEFAULT 0 NOT NULL,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SYS_SETTING PRIMARY KEY (SETTING_ID),
    CONSTRAINT UQ_SS_TENANT_KEY UNIQUE (TENANT_ID, SETTING_KEY),
    CONSTRAINT CHK_SS_VTYPE CHECK (VALUE_TYPE IN ('STRING','NUMBER','BOOLEAN','JSON','DURATION')),
    CONSTRAINT CHK_SS_SENSITIVE CHECK (IS_SENSITIVE IN (0, 1))
);

CREATE INDEX IDX_SS_TENANT ON SYSTEM_SETTINGS (TENANT_ID);
CREATE INDEX IDX_SS_KEY ON SYSTEM_SETTINGS (SETTING_KEY);
