package io.innait.wiam.authorchestrator.statemachine;

public enum AuthEvent {
    LOGIN_ID_SUBMITTED,
    PRIMARY_CHALLENGE_ISSUED,
    PRIMARY_FACTOR_VERIFIED,
    PRIMARY_FACTOR_FAILED,
    MFA_CHALLENGE_ISSUED,
    MFA_FACTOR_VERIFIED,
    MFA_FACTOR_FAILED,
    MAGIC_LINK_SENT,
    MAGIC_LINK_VERIFIED,
    ONBOARDING_STARTED,
    FIDO_ENROLLMENT_STARTED,
    FIDO_ENROLLMENT_COMPLETED,
    AUTH_COMPLETED,
    AUTH_ABORTED,
    TIMEOUT
}
