-- ============================================================================
-- InnaIT WIAM 5.0 - INNAIT_POLICY Schema
-- V001: Password, MFA, auth policies, and policy bindings
-- ============================================================================

--------------------------------------------------------
-- PASSWORD_POLICIES
--------------------------------------------------------
CREATE TABLE PASSWORD_POLICIES (
    PASSWORD_POLICY_ID   RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    POLICY_NAME          VARCHAR2(255)     NOT NULL,
    MIN_LENGTH           NUMBER(3)         DEFAULT 12 NOT NULL,
    MAX_LENGTH           NUMBER(3)         DEFAULT 128 NOT NULL,
    REQUIRE_UPPERCASE    NUMBER(1)         DEFAULT 1 NOT NULL,
    REQUIRE_LOWERCASE    NUMBER(1)         DEFAULT 1 NOT NULL,
    REQUIRE_DIGIT        NUMBER(1)         DEFAULT 1 NOT NULL,
    REQUIRE_SPECIAL      NUMBER(1)         DEFAULT 1 NOT NULL,
    MAX_REPEATED_CHARS   NUMBER(2)         DEFAULT 3 NOT NULL,
    HISTORY_COUNT        NUMBER(3)         DEFAULT 12 NOT NULL,
    MAX_AGE_DAYS         NUMBER(5)         DEFAULT 90 NOT NULL,
    MIN_AGE_DAYS         NUMBER(5)         DEFAULT 1 NOT NULL,
    LOCKOUT_THRESHOLD    NUMBER(3)         DEFAULT 5 NOT NULL,
    LOCKOUT_DURATION_MIN NUMBER(5)         DEFAULT 30 NOT NULL,
    IS_DEFAULT           NUMBER(1)         DEFAULT 0 NOT NULL,
    STATUS               VARCHAR2(20)      DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PWD_POLICY PRIMARY KEY (PASSWORD_POLICY_ID),
    CONSTRAINT CHK_PP_UPPER CHECK (REQUIRE_UPPERCASE IN (0, 1)),
    CONSTRAINT CHK_PP_LOWER CHECK (REQUIRE_LOWERCASE IN (0, 1)),
    CONSTRAINT CHK_PP_DIGIT CHECK (REQUIRE_DIGIT IN (0, 1)),
    CONSTRAINT CHK_PP_SPECIAL CHECK (REQUIRE_SPECIAL IN (0, 1)),
    CONSTRAINT CHK_PP_DEFAULT CHECK (IS_DEFAULT IN (0, 1)),
    CONSTRAINT CHK_PP_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE'))
);

CREATE INDEX IDX_PP_TENANT ON PASSWORD_POLICIES (TENANT_ID);

--------------------------------------------------------
-- MFA_POLICIES
--------------------------------------------------------
CREATE TABLE MFA_POLICIES (
    MFA_POLICY_ID        RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    POLICY_NAME          VARCHAR2(255)     NOT NULL,
    ENFORCEMENT_MODE     VARCHAR2(20)      DEFAULT 'OPTIONAL' NOT NULL,
    ALLOWED_METHODS      CLOB              DEFAULT '["TOTP","FIDO"]',
    REMEMBER_DEVICE_DAYS NUMBER(5)         DEFAULT 30 NOT NULL,
    GRACE_PERIOD_DAYS    NUMBER(5)         DEFAULT 7 NOT NULL,
    IS_DEFAULT           NUMBER(1)         DEFAULT 0 NOT NULL,
    STATUS               VARCHAR2(20)      DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_MFA_POLICY PRIMARY KEY (MFA_POLICY_ID),
    CONSTRAINT CHK_MP_ENFORCE CHECK (ENFORCEMENT_MODE IN ('REQUIRED','OPTIONAL','ADAPTIVE','DISABLED')),
    CONSTRAINT CHK_MP_METHODS CHECK (ALLOWED_METHODS IS JSON),
    CONSTRAINT CHK_MP_DEFAULT CHECK (IS_DEFAULT IN (0, 1)),
    CONSTRAINT CHK_MP_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE'))
);

CREATE INDEX IDX_MP_TENANT ON MFA_POLICIES (TENANT_ID);

--------------------------------------------------------
-- AUTH_POLICIES (conditional access with SpEL expressions)
--------------------------------------------------------
CREATE TABLE AUTH_POLICIES (
    AUTH_POLICY_ID       RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    POLICY_NAME          VARCHAR2(255)     NOT NULL,
    DESCRIPTION          VARCHAR2(1000),
    PRIORITY             NUMBER(5)         DEFAULT 100 NOT NULL,
    RULE_EXPRESSION      VARCHAR2(4000)    NOT NULL,
    ACTION               VARCHAR2(30)      DEFAULT 'ALLOW' NOT NULL,
    MFA_REQUIRED         NUMBER(1)         DEFAULT 0 NOT NULL,
    REQUIRED_AUTH_LEVEL  NUMBER(2)         DEFAULT 1 NOT NULL,
    IS_DEFAULT           NUMBER(1)         DEFAULT 0 NOT NULL,
    STATUS               VARCHAR2(20)      DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION              NUMBER(19)        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_AUTH_POLICY PRIMARY KEY (AUTH_POLICY_ID),
    CONSTRAINT CHK_AP_ACTION CHECK (ACTION IN ('ALLOW','DENY','MFA_STEPUP','REVIEW')),
    CONSTRAINT CHK_AP_MFA CHECK (MFA_REQUIRED IN (0, 1)),
    CONSTRAINT CHK_AP_DEFAULT CHECK (IS_DEFAULT IN (0, 1)),
    CONSTRAINT CHK_AP_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE'))
);

CREATE INDEX IDX_AP_TENANT ON AUTH_POLICIES (TENANT_ID);
CREATE INDEX IDX_AP_PRIORITY ON AUTH_POLICIES (TENANT_ID, PRIORITY);

--------------------------------------------------------
-- POLICY_BINDINGS
--------------------------------------------------------
CREATE TABLE POLICY_BINDINGS (
    BINDING_ID           RAW(16)           DEFAULT SYS_GUID() NOT NULL,
    TENANT_ID            RAW(16)           NOT NULL,
    POLICY_TYPE          VARCHAR2(30)      NOT NULL,
    POLICY_ID            RAW(16)           NOT NULL,
    TARGET_TYPE          VARCHAR2(30)      NOT NULL,
    TARGET_ID            RAW(16)           NOT NULL,
    IS_ACTIVE            NUMBER(1)         DEFAULT 1 NOT NULL,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_POLICY_BIND PRIMARY KEY (BINDING_ID),
    CONSTRAINT UQ_PB_POLICY_TARGET UNIQUE (POLICY_ID, TARGET_TYPE, TARGET_ID),
    CONSTRAINT CHK_PB_PTYPE CHECK (POLICY_TYPE IN ('PASSWORD','MFA','AUTH')),
    CONSTRAINT CHK_PB_TTYPE CHECK (TARGET_TYPE IN ('TENANT','APPLICATION','GROUP','ROLE','ORG_UNIT','USER')),
    CONSTRAINT CHK_PB_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

CREATE INDEX IDX_PB_TENANT ON POLICY_BINDINGS (TENANT_ID);
CREATE INDEX IDX_PB_POLICY ON POLICY_BINDINGS (POLICY_ID);
CREATE INDEX IDX_PB_TARGET ON POLICY_BINDINGS (TARGET_TYPE, TARGET_ID);
